apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: taski
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html/;

      location /api/ {
        proxy_pass http://backend-service:8000/;
      }

      location / {
        proxy_pass http://frontend-service:3000/;
      }
    }
