services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: ju1ie/taski_backend
    container_name: taski_backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ju1ie/taski_frontend
    container_name: taski_frontend
    ports:
      - "3000:80"

  nginx:
    image: nginx:1.25-alpine
    container_name: taski_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    
