name: CI/CD Deploy Taski

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZATION }}

      - name: Build and push Docker image to Yandex.Cloud Container Registry
        env:
          CR_REGISTRY: crp0sq7kl26fmbmirs4m
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG ./frontend/
          docker push cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG ./backend/
          docker push cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG ./nginx/
          docker push cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG
      
      - name: Connect to VPC-Server
        uses: appleboy/ssh-action@master
        env:
          OAUTH_TOKEN: y0__wgBEJLw0oUHGMHdEyCsyouBEv_-CJnhXsVzZtn2kB9RFdRIZTAk
          CR_REGISTRY: crp0sq7kl26fmbmirs4m
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: 84.201.171.27
          username: julie
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | 
            echo $OAUTH_TOKEN|docker login --username oauth --password-stdin cr.yandex
