name: CI/CD Deploy Taski

on:
  push:
    branches:
      - main
    paths: 
      - 'frontend/**'
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.VPC_SSH_KEY }}
