name: CI/CD Deploy Taski
 
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZATION }}

      - name: Build and push Docker image to Yandex.Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG ./frontend/
          docker push cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG ./backend/
          docker push cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG ./nginx/
          docker push cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG
      
      - name: Connect to VPC-Server
        uses: appleboy/ssh-action@master
        env:
          OAUTH_TOKEN: ${{ secrets.TOKEN }}
          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: 84.201.171.27
          username: julie
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | 
            echo ${{ secrets.TOKEN }}|docker login --username oauth --password-stdin cr.yandex
            docker kill $(docker ps -q) &> /dev/null
            docker rmi -f $(docker images -qa)
            docker system prune --all --force
            docker run -p 3000:3000 -d cr.yandex/${{ secrets.CR_REGISTRY }}/frontend:${{ github.sha }}
            docker run -p 8000:8000 -d cr.yandex/${{ secrets.CR_REGISTRY }}/backend:${{ github.sha }}
            docker run -p 80:80 --net=host -d cr.yandex/${{ secrets.CR_REGISTRY }}/nginx:${{ github.sha }}
