name: Kubernetes (K8s) CI/CD Deploy Taski

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest
            
    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker

    - name: Set up Docker environment in Minikube
      run: |
        eval $(minikube -p minikube docker-env)

    - name: Build backend image and load into Minikube
      run: |
        docker build -t taski-backend:v1 -f backend/Dockerfile .
        minikube image load taski-backend:v1

    - name: Build frontend image and load into Minikube
      run: |
        docker build -t taski-frontend:v1 -f frontend/Dockerfile .
        minikube image load taski-frontend:v1

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s.yaml
        kubectl apply -f service.yaml

    - name: Wait for pods to be ready
      run: |
        kubectl get pods

    - name: Minikube cleanup
      if: always()
      run: |
        minikube stop
        minikube delete
