name: CI/CD Deploy Taski

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZATION }}
      
      - name: Connect to VPC-Server
        uses: appleboy/ssh-action@master
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          CR_REGISTRY: crp0sq7kl26fmbmirs4m
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: 84.201.171.27
          username: julie
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | 
            mkdir zopa
